spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: library
    password: library
    driver-class-name: org.postgresql.Driver
  liquibase:
    changeLog: "classpath:/db/changelog-master.yaml"